export const MESSAGE_TRANSLATION = "MESSAGE_TRANSLATION";
export const MESSAGE = "MESSAGE";
export const MESSAGES = "MESSAGES";

export const ARGUMENT_TRANSLATION = "ARGUMENT_TRANSLATION";
export const ARGUMENT = "ARGUMENT";
export const ARGUMENTS = "ARGUMENTS";

export const CADENCE = "CADENCE";

export const INTERFACE = "INTERFACE";

export const TYPE = "TYPE";

export const DEPENDENCY = "DEPENDENCY";
export const DEPENDENCIES = "DEPENDENCIES";
export const DEPENDENCY_CONTRACT = "DEPENDENCY_CONTRACT";
export const DEPENDENCY_CONTRACT_BY_NETWORK = "DEPENDENCY_CONTRACT_BY_NETWORK";
